export const levelsList = [
  "pre3A",
  "pre3B",
  "pre45A",
  "pre45B",
  "whiteRibA",
  "whiteRibB",
  "redRibA",
  "redRibB",
  "blueRibA",
  "blueRibB",
  "bronzeMedA",
  "bronzeMedB",
  "silverMedA",
  "silverMedB",
  "begBoys",
  "intBoys",
  "begTumb",
  "intTumb",
  "cheerTumb",
  "airAware",
  "hotShotFoun",
  "hotShotAdv",
  "hotTots",
  "xcelA",
  "xcelSilver",
  "xcelGold",
  "level3",
  "level4",
  "optionalA",
  "optionalB",
];

export const levelsInfo = {
  pre3A: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  pre3B: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  pre45A: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  pre45B: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  whiteRibA: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  whiteRibB: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  redRibA: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  redRibB: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  blueRibA: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  blueRibB: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  bronzeMedA: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  bronzeMedB: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  silverMedA: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  silverMedB: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  begBoys: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  intBoys: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  begTumb: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  intTumb: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  cheerTumb: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  airAware: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  hotShotFoun: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  hotShotAdv: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  hotTots: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  xcelA: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  xcelSilver: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  xcelGold: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  level3: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  level4: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  optionalA: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
  optionalB: {
    classesPerWeek: 2,
    eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
    coaches: ["Courtney"],
  },
};

// For generating level info

// for (const level of levelsList) {
//   levelsInfo[level] = {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   };
// }

export const times = {
  "2:30": "",
  "2:35": "",
  "2:40": "",
  "2:45": "",
  "2:50": "",
  "2:55": "",
  "3:00": "",
  "3:05": "",
  "3:10": "",
  "3:15": "",
  "3:20": "",
  "3:25": "",
  "3:30": "",
  "3:35": "",
  "3:40": "",
  "3:45": "",
  "3:50": "",
  "3:55": "",
  "4:00": "",
  "4:05": "",
  "4:10": "",
  "4:15": "",
  "4:20": "",
  "4:25": "",
  "4:30": "",
  "4:35": "",
  "4:40": "",
  "4:45": "",
  "4:50": "",
  "4:55": "",
  "5:00": "",
  "5:05": "",
  "5:10": "",
  "5:15": "",
  "5:20": "",
  "5:25": "",
  "5:30": "",
  "5:35": "",
  "5:40": "",
  "5:45": "",
  "5:50": "",
  "5:55": "",
  "6:00": "",
  "6:05": "",
  "6:10": "",
  "6:15": "",
  "6:20": "",
  "6:25": "",
  "6:30": "",
  "6:35": "",
  "6:40": "",
  "6:45": "",
  "6:50": "",
  "6:55": "",
  "7:00": "",
  "7:05": "",
  "7:10": "",
  "7:15": "",
  "7:20": "",
  "7:25": "",
  "7:30": "",
  "7:35": "",
  "7:40": "",
  "7:45": "",
  "7:50": "",
  "7:55": "",
};

export const events = ["vault", "bars", "beam", "floor"];

export const fullSchedule = {
  mondayA: {},
  mondayB: {},
  tuesdayA: {},
  tuesdayB: {},
  wednesdayA: {},
  wednesdayB: {},
  thursdayA: {},
  thursdayB: {},
  fridayA: {},
  fridayB: {},
  saturdayA: {},
  saturdayB: {},
};
