export const levelsList = [
  "pre3A",
  "pre3B",
  "pre45A",
  "pre45B",
  "whiteRibA",
  "whiteRibB",
  "redRibA",
  "redRibB",
  "blueRibA",
  "blueRibB",
  "bronzeMedA",
  "bronzeMedB",
  "silverMedA",
  "silverMedB",
  "begBoys",
  "intBoys",
  "begTumb",
  "intTumb",
  "cheerTumb",
  "airAware",
  "hotShotFoun",
  "hotShotAdv",
  "hotTots",
  "xcelA",
  "xcelSilver",
  "xcelGold",
  "level3",
  "level4",
  "optionalA",
  "optionalB",
];

export const levelsInfo = {
  pre3A: { classesPerWeek: 2, coaches: [] },
  pre3B: { classesPerWeek: 2, coaches: [] },
  pre45A: { classesPerWeek: 2, coaches: [] },
  pre45B: { classesPerWeek: 2, coaches: [] },
  whiteRibA: { classesPerWeek: 2, coaches: [] },
  whiteRibB: { classesPerWeek: 2, coaches: [] },
  redRibA: { classesPerWeek: 2, coaches: [] },
  redRibB: { classesPerWeek: 2, coaches: [] },
  blueRibA: { classesPerWeek: 2, coaches: [] },
  blueRibB: { classesPerWeek: 2, coaches: [] },
  bronzeMedA: { classesPerWeek: 2, coaches: [] },
  bronzeMedB: { classesPerWeek: 2, coaches: [] },
  silverMedA: { classesPerWeek: 2, coaches: [] },
  silverMedB: { classesPerWeek: 2, coaches: [] },
  begBoys: { classesPerWeek: 2, coaches: [] },
  intBoys: { classesPerWeek: 2, coaches: [] },
  begTumb: { classesPerWeek: 2, coaches: [] },
  intTumb: { classesPerWeek: 2, coaches: [] },
  cheerTumb: { classesPerWeek: 2, coaches: [] },
  airAware: { classesPerWeek: 2, coaches: [] },
  hotShotFoun: { classesPerWeek: 2, coaches: [] },
  hotShotAdv: { classesPerWeek: 2, coaches: [] },
  hotTots: { classesPerWeek: 2, coaches: [] },
  xcelA: { classesPerWeek: 2, coaches: [] },
  xcelSilver: { classesPerWeek: 2, coaches: [] },
  xcelGold: { classesPerWeek: 2, coaches: [] },
  level3: { classesPerWeek: 2, coaches: [] },
  level4: { classesPerWeek: 2, coaches: [] },
  optionalA: { classesPerWeek: 2, coaches: [] },
  optionalB: { classesPerWeek: 2, coaches: [] },
};
//   pre3A: {
//     classesPerWeek: 2,
//     eventsAndDurations: {
//       warmup: 10,
//       preVault: 10,
//       jfk: 10,
//       preBeam: 10,
//       preFloor: 10,
//       trampA: 10,
//       trampB: 10,
//       recTT: 10,
//     },
//     coaches: ["Courtney"],
//   },
//   pre3B: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   pre45A: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   pre45B: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   whiteRibA: {
//     classesPerWeek: 2,
//     eventsAndDurations: {
//       warmup: 15,
//       condition: 15,
//       recVault: 15,
//       recBars: 15,
//       recBeam: 15,
//       recFloorA: 15,
//       recFloorB: 15,
//       recTT: 15,
//       recTumbleStrip: 15,
//       trampA: 15,
//       trampB: 15,
//     },
//     coaches: ["Courtney"],
//   },
//   whiteRibB: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   redRibA: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   redRibB: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   blueRibA: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   blueRibB: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   bronzeMedA: {
//     classesPerWeek: 2,
//     eventsAndDurations: {
//       warmup: 20,
//       condition: 20,
//       recVault: 20,
//       recBars: 20,
//       recBeam: 20,
//       recFloorA: 20,
//       recFloorB: 20,
//       recTT: 20,
//       teamTT: 20,
//       recTumbleStrip: 20,
//       trampA: 20,
//       trampB: 20,
//     },
//     coaches: ["Courtney"],
//   },
//   bronzeMedB: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   silverMedA: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   silverMedB: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   begBoys: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   intBoys: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   begTumb: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   intTumb: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   cheerTumb: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   airAware: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   hotTots: {
//     classesPerWeek: 2,
//     eventsAndDurations: {
//       warmup: 15,
//       recVault: 15,
//       teamStarBarsB: 15,
//       recBeam: 15,
//       recFloor: 15,
//     },
//     coaches: ["Courtney"],
//   },
//   hotShotFoun: {
//     classesPerWeek: 2,
//     eventsAndDurations: {
//       warmup: 15,
//       recVault: 20,
//       teamStarBarsA: 15,
//       teamStarBarsB: 20,
//       recBeam: 15,
//       teamLowBeam: 20,
//       recFloor: 15,
//     },
//     coaches: ["Courtney"],
//   },
//   hotShotAdv: {
//     classesPerWeek: 2,
//     eventsAndDurations: {
//       warmup: 30,
//       condition: 30,
//       recVault: 30,
//       teamVault: 30,
//       teamBars: 30,
//       teamStarBarsA: 30,
//       teamBeam: 30,
//       recFloorA: 30,
//       recFloorB: 30,
//       teamFloor: 30,
//     },
//     coaches: ["Courtney"],
//   },
//   xcelA: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   xcelSilver: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   xcelGold: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   level3: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   level4: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   optionalA: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
//   optionalB: {
//     classesPerWeek: 2,
//     eventsAndDurations: { vault: 15, bars: 30, beam: 45, floor: 10 },
//     coaches: ["Courtney"],
//   },
// };

// For generating level info
// const newnew = {};
// for (const level of levelsList) {
//   newnew[level] = {
//     classesPerWeek: 2,
//     coaches: [],
//   };
// }
// console.log(newnew);

// for generating times:

const endings = [
  ":00:00",
  ":05:00",
  ":10:00",
  ":15:00",
  ":20:00",
  ":25:00",
  ":30:00",
  ":35:00",
  ":40:00",
  ":45:00",
  ":50:00",
  ":55:00",
];

// for (let i = 14; i <= 19; i++) {
//   for (const ending of endings) {
//     const stringI = i.toString();
//     console.log(stringI + ending);
//   }
// }

export const times = [
  "14:30:00",
  "14:35:00",
  "14:40:00",
  "14:45:00",
  "14:50:00",
  "14:55:00",
  "15:00:00",
  "15:05:00",
  "15:10:00",
  "15:15:00",
  "15:20:00",
  "15:25:00",
  "15:30:00",
  "15:35:00",
  "15:40:00",
  "15:45:00",
  "15:50:00",
  "15:55:00",
  "16:00:00",
  "16:05:00",
  "16:10:00",
  "16:15:00",
  "16:20:00",
  "16:25:00",
  "16:30:00",
  "16:35:00",
  "16:40:00",
  "16:45:00",
  "16:50:00",
  "16:55:00",
  "17:00:00",
  "17:05:00",
  "17:10:00",
  "17:15:00",
  "17:20:00",
  "17:25:00",
  "17:30:00",
  "17:35:00",
  "17:40:00",
  "17:45:00",
  "17:50:00",
  "17:55:00",
  "18:00:00",
  "18:05:00",
  "18:10:00",
  "18:15:00",
  "18:20:00",
  "18:25:00",
  "18:30:00",
  "18:35:00",
  "18:40:00",
  "18:45:00",
  "18:50:00",
  "18:55:00",
  "19:00:00",
  "19:05:00",
  "19:10:00",
  "19:15:00",
  "19:20:00",
  "19:25:00",
  "19:30:00",
  "19:35:00",
  "19:40:00",
  "19:45:00",
  "19:50:00",
  "19:55:00",
];

export const events = [
  "warmup",
  "condition",
  "teamVault",
  "teamBars",
  "teamBeam",
  "teamFloor",
  "teamTT",
  "teamStarBarsA",
  "teamStarBarsB",
  "teamLowBeam",
  "teamRodFloor",
  "recVault",
  "recBars",
  "recBeam",
  "recFloorA",
  "recFloorB",
  "recTT",
  "recTumbleStrip",
  "preVault",
  "jfk",
  "preBeam",
  "preFloor",
  "trampA",
  "trampB",
];

// CONFLICTS OK:
// warmup and conditioning

export const fullSchedule = {
  mondayA: {},
  mondayB: {},
  tuesdayA: {},
  tuesdayB: {},
  wednesdayA: {},
  wednesdayB: {},
  thursdayA: {},
  thursdayB: {},
  fridayA: {},
  fridayB: {},
  saturdayA: {},
  saturdayB: {},
};

// "2:30",
// "2:35",
// "2:40",
// "2:45",
// "2:50",
// "2:55",
// "3:00",
// "3:05",
// "3:10",
// "3:15",
// "3:20",
// "3:25",
// "3:30",
// "3:35",
// "3:40",
// "3:45",
// "3:50",
// "3:55",
// "4:00",
// "4:05",
// "4:10",
// "4:15",
// "4:20",
// "4:25",
// "4:30",
// "4:35",
// "4:40",
// "4:45",
// "4:50",
// "4:55",
// "5:00",
// "5:05",
// "5:10",
// "5:15",
// "5:20",
// "5:25",
// "5:30",
// "5:35",
// "5:40",
// "5:45",
// "5:50",
// "5:55",
// "6:00",
// "6:05",
// "6:10",
// "6:15",
// "6:20",
// "6:25",
// "6:30",
// "6:35",
// "6:40",
// "6:45",
// "6:50",
// "6:55",
// "7:00",
// "7:05",
// "7:10",
// "7:15",
// "7:20",
// "7:25",
// "7:30",
// "7:35",
// "7:40",
// "7:45",
// "7:50",
// "7:55",
